# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkTo8cY7D9EW9brf4JQrwwObOEePVBvT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv("Iris.csv")
df.head()

df.head()
from sklearn.preprocessing import LabelEncoder,StandardScaler
le=LabelEncoder()
df["Species"]=le.fit_transform(df["Species"])
df.head()
sd=StandardScaler()

df.head()
x=df.drop(["Species","Id"],axis=1)
y=df["Species"]

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
from tensorflow.keras import optimizers
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)

# Fit scaler ONLY on training data
x_train_scaled = sd.fit_transform(x_train)

# Use the already-fitted scaler on test data
x_test_scaled = sd.transform(x_test)

import numpy as np

x_train_scaled = np.asarray(x_train_scaled, dtype=np.float32)
x_test_scaled = np.asarray(x_test_scaled, dtype=np.float32)

y_train = np.asarray(y_train, dtype=np.int32)
y_test = np.asarray(y_test, dtype=np.int32)
model = keras.Sequential([
    layers.Input(shape=(4,)),
    layers.Dense(16, activation="relu"),
    layers.Dense(8, activation="relu"),
    layers.Dense(3, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    x_train_scaled,
    y_train,
    validation_data=(x_test_scaled, y_test),
    epochs=100,
    batch_size=16,
    verbose=1
)

loss, accuracy = model.evaluate(x_test_scaled, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)
model.save("iris_model.keras")

import joblib

joblib.dump(sd, "scaler.pkl")

